functions:
- getVehiclePlatingWeightInfo:
    method: GET
    path: /dvla-ants/
    function: getVehiclePlatingWeightInfo
serverless:
  basePath: /${BRANCH}
  port: 3006
endpoints:
  local-global:
    params:
      apiVersion: '2015-03-31'
      region: eu-west-1
      endpoint: http://localhost:4000
    functions:
      getVehiclePlatingWeightInfo:
        name: cvs-svc-global-dev-getVehiclePlatingWeightInfo
  remote:
    params:
      apiVersion: '2015-03-31'
    functions:
      getVehiclePlatingWeightInfo:
        name: lec-test-results-${BRANCH}